#pragma config(Sensor, S2,     leftTouch,      sensorEV3_Touch)
#pragma config(Sensor, S3,     rightTouch,      sensorEV3_Touch)
// #pragma config(Sensor, S2,     rightTouch,     sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ************************************************************
// File:  			Monopoly.c
// Assignment:  Clayfield College Year 8 Robotics - Monopoly
// Author:  		Jennifer Lollback
// Date:				08/11/2018
// ************************************************************

#pragma DebuggerWindows("debugStream")

#include "BoardActions.h"
#include "Utils.h"

// Global variables
int gPlayerPosition = 0;
int gCashOnHand = 1500;
int gNoOfThrows = 0;

// Move the Lego motor around the board
void MovePosition(int NoOfSpaces)
{
	float degreesPerSpace = 360/(float)BOARD_POSITIONS;
	resetMotorEncoder(motorA);
	setMotorTarget(motorA, NoOfSpaces*degreesPerSpace, 20);
	waitUntilMotorStop(motorA);
}

// Main program
task main()
{
	clearDebugStream();
	writeDebugStreamLine("Game starting - total positions = %d", BOARD_POSITIONS);

	// Initialisation tasks
	SetupBoard();
	SetupActions();
	SetupChanceActions();

	// Turn off brick LED so that it will flash during game play
	setLEDColor(ledOff);

	while (true)
	{
		// Press the left button for game play
		if (SensorValue(leftTouch) == 1)
		{
			gNoOfThrows++;

			DisplayLines("*Rolling Dice*", "", "", 0);
			wait1Msec(500);

			int dice = RollDice();
			writeDebugStreamLine("Roll: %d", dice);
			MovePosition(dice);

			gPlayerPosition = gPlayerPosition + dice;
			if (gPlayerPosition >= BOARD_POSITIONS)  // Has player passed go?
			{
				gPlayerPosition = gPlayerPosition - BOARD_POSITIONS;
				gCashOnHand+= 200;
				writeDebugStreamLine("Passed go, cash = $%d", gCashOnHand);
			}
			writeDebugStreamLine("Position: %d, %s, Cash: $%d", gPlayerPosition, boardLayout[gPlayerPosition], gCashOnHand);

			switch(gPlayerPosition)
			{
			case 0:  // Passed Go
				DisplayLines("Landed on Go!", "", "", +200);
				// No need to update gCashOnHand, this has already been done
				break;

			case 1:  // Ashburn
			case 2:  // Radcliffe
			case 5:	 // Youngman
			case 7:	 // Henderson
			case 8:  // Campbell
			case 11: // Gibson
				int randomAction = GetRandom(0, MAX_ACTIONS - 1);
				DisplayLines(gHouseActions[randomAction].lineOne,
						gHouseActions[randomAction].lineTwo,
						gHouseActions[randomAction].lineThree,
						gHouseActions[randomAction].amount);
				gCashOnHand += gHouseActions[randomAction].amount;
				break;

			case 3:  // Chance
			case 6:  // Chance
			case 9:	 // Chance
			case 13: // Chance
			int randomChance = GetRandom(0, MAX_CHANCE - 1);
				DisplayLines(gChanceActions[randomChance].lineOne,
						gChanceActions[randomChance].lineTwo,
						gChanceActions[randomChance].lineThree,
						gChanceActions[randomChance].amount);
				gCashOnHand += gChanceActions[randomChance].amount;
				break;

			case 4:  // Get 3 Infringements
				DisplayLines("Infringements", "Receive 3", "infringements", -250);
				gCashOnHand += -250;
				break;

			case 10:  // Lunch
				DisplayLines("Lunch", "Didn't drink", "water at lunch.", -100);
				gCashOnHand += -100;
				break;

			case 12:  // Eagle Junction Train Station
			DisplayLines("Monthly train", "fares increase", "", -100);
				gCashOnHand += -100;
				break;

			default:
				writeDebugStreamLine("Unknown case %d value, default handler used", gPlayerPosition);
				break;
			}

			wait1Msec(1000);
		} // end leftTouch

		// Press the right button for game statistics
		if (SensorValue(rightTouch) == 1)
		{
			// Display the game statistics to the user
			string balance;
			sprintf(balance, "Balance: $%-d", gCashOnHand);
			string throws;
			sprintf(throws, "Throws: %d", gNoOfThrows);

			DisplayLines(balance, throws, "", 0);

		} // end rightTouch
	} // end true
} // end main
